import type { IconSvgElement } from "@hugeicons/react";
import {
  RemoveCircleIcon,
  ChatFeedback01Icon,
  Add01Icon,
  Alert02Icon,
  AlertCircleIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  BadgeIcon,
  PrinterIcon,
  ChatDoneIcon,
  ChatFavouriteIcon,
  BalanceScaleIcon,
  ThumbsUpIcon,
  ThumbsDownIcon,
  BankIcon,
  BeakerIcon,
  BlockedIcon,
  Book01Icon,
  PercentIcon,
  ListIcon,
  EuroCircleIcon,
  BookOpen01Icon,
  Bookmark01Icon,
  Brain01Icon,
  Building01Icon,
  Calendar03Icon,
  CalendarCheckIcon,
  CalendarOffIcon,
  Camera01Icon,
  Camera02Icon,
  CameraAdd01Icon,
  Cancel01Icon,
  Cancel02Icon,
  Castle02Icon,
  CastleIcon,
  MailOpenIcon,
  CheckIcon,
  CheckmarkBadge01Icon,
  CheckmarkCircle02Icon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChinaTempleIcon,
  ChurchIcon,
  CircleIcon,
  ClipboardIcon,
  Clock01Icon,
  Compass01Icon,
  ConstructionIcon,
  ContrastIcon,
  Copy01Icon,
  CreditCardIcon,
  CreditCardNotAcceptIcon,
  Crown02Icon,
  DashboardCircleIcon,
  DashboardSquareAddIcon,
  Delete01Icon,
  Diamond01Icon,
  DomeIcon,
  Download01Icon,
  DropletIcon,
  Edit02Icon,
  ViewIcon,
  SparkleIcon,
  EyeOffIcon,
  Facebook01Icon,
  FavouriteIcon,
  File01Icon,
  FileTextIcon,
  FileUploadIcon,
  FilterMailIcon,
  Flag02Icon,
  FlameIcon,
  FlashIcon,
  Folder01Icon,
  GalleryThumbnailsIcon,
  GlobalSearchIcon,
  Globe02Icon,
  GridIcon,
  HandshakeIcon,
  ZapOffIcon,
  HelpCircleIcon,
  HistoryIcon,
  Home07Icon,
  HourglassIcon,
  IdCardIcon,
  CustomerSupportIcon,
  LinkBackwardIcon,
  Location06Icon,
  CircleCheckIcon,
  Image01Icon,
  Image02Icon,
  ImageAdd01Icon,
  InboxIcon,
  InboxUploadIcon,
  InformationCircleIcon,
  InstagramIcon,
  Key01Icon,
  LaptopPhoneSyncIcon,
  LaurelWreathLeft03Icon,
  ChatCancelIcon,
  LaurelWreath01Icon,
  LaurelWreathFirst01Icon,
  Link01Icon,
  LockKeyholeIcon,
  GiftCardIcon,
  LockOpenIcon,
  GridTableIcon,
  CombineIcon,
  Logout01Icon,
  LoyaltyCardIcon,
  MagicWand01Icon,
  Mail01Icon,
  MailAtSign01Icon,
  PlayCircle02Icon,
  MailOpen01Icon,
  Mailbox01Icon,
  CheckCheckIcon,
  MapIcon,
  MaskTheater02Icon,
  BackgroundIcon,
  Megaphone03Icon,
  MenuSquareIcon,
  MicroscopeIcon,
  ListViewIcon,
  Moon01Icon,
  Mosque01Icon,
  Appointment02Icon,
  MusicNote01Icon,
  NetworkIcon,
  NewspaperIcon,
  Note01Icon,
  NoteEditIcon,
  BellIcon,
  BellRingIcon,
  ArrowReloadHorizontalIcon,
  BellOffIcon,
  Package01Icon,
  PaintBrush01Icon,
  PaintBrush02Icon,
  PartyIcon,
  PauseCircleIcon,
  PauseIcon,
  PawPrintIcon,
  PencilIcon,
  PhoneCallIcon,
  Remove01Icon,
  PuzzleIcon,
  AddCircleIcon,
  ReceiptTextIcon,
  Refresh01Icon,
  StudentCardIcon,
  RocketIcon,
  SaleTag01Icon,
  SavingsIcon,
  SchoolIcon,
  Search01Icon,
  SendHorizontalIcon,
  Settings03Icon,
  Shield01Icon,
  GiftIcon,
  MessageIncoming01Icon,
  MessageMultiple01Icon,
  Shield02Icon,
  SkullIcon,
  SlidersHorizontalIcon,
  SmileIcon,
  SparklesIcon,
  StarsIcon,
  Store01Icon,
  Sun01Icon,
  Tag01Icon,
  PaintbrushIcon,
  TextFontIcon,
  Ticket01Icon,
  Timer01Icon,
  ToggleOffIcon,
  ToggleOnIcon,
  TokenCircleIcon,
  HashtagIcon,
  Tree01Icon,
  TrophyIcon,
  UserAdd02Icon,
  UserCheck01Icon,
  UserGroup02Icon,
  GraduationCapIcon,
  StarIcon,
  User02Icon,
  UserMultiple02Icon,
  UserRemove01Icon,
  UserSettings02Icon,
  StarSquareIcon,
  WebhookIcon,
  WellnessIcon,
  AttachmentSquareIcon,
  Yoga01Icon,
  BulbChargingIcon,
  Quiz03Icon,
  IdentityCardIcon,
  Medal04Icon,
  HonourStarIcon,
  AtomicPowerIcon,
  BowArrowIcon,
  ChartRingIcon,
  Note03Icon,
  Briefcase04Icon,
  GlobeIcon,
  PoliceBadgeIcon,
  SourceCodeIcon,
  ArrowRightFromLineIcon,
  CoinsEuroIcon,
  ArrowRightToLineIcon,
  TextBoldIcon,
  TextItalicIcon,
  TextAlignLeftIcon,
  TextAlignCenterIcon,
  TextAlignRightIcon,
  HeadingIcon,
  LeftToRightBlockQuoteIcon,
  SolidLine01Icon,
  Unlink01Icon,
  Upload01Icon,
  AppleIcon,
  SmartPhone01Icon,
  CheckmarkSquare02Icon,
  SquareIcon,
  LinkSquare02Icon,
  SwordIcon,
  SwordsIcon,
  AxeIcon,
  Knife01Icon,
  KnightShieldIcon,
  CrownIcon,
  ScrollIcon,
  PotionIcon,
  DiceIcon,
  CardsIcon,
  ChessKnightIcon,
  ChessKingIcon,
  GhostIcon,
  MoonStarIcon,
  MoonEclipseIcon,
  SnowflakeIcon,
  TornadoIcon,
  RainbowIcon,
  MountainIcon,
  IslandIcon,
  TreesIcon,
  Leaf01Icon,
  FlowerIcon,
  MushroomIcon,
  FishIcon,
  BirdIcon,
  HorseIcon,
  FeatherIcon,
  AnchorIcon,
  ShipIcon,
  LighthouseIcon,
  BridgeIcon,
  Undo03Icon,
  TentIcon,
  CampfireIcon,
  GoldIngotsIcon,
  MoneyBagIcon,
  HammerIcon,
  BombIcon,
  Target02Icon,
  BoneIcon,
  HeartbreakIcon,
  FirstAidKitIcon,
  HandPrayerIcon,
  BeerIcon,
  PrisonIcon,
  GavelIcon,
  DrumIcon,
  GuitarIcon,
  DnaIcon,
  AlienIcon,
  RobotIcon,
  UfoIcon,
  BiohazardIcon,
  CloverIcon,
  LanternIcon,
  MaskIcon,
  PyramidIcon,
  GunIcon,
  EyeIcon,
} from "@hugeicons/core-free-icons";

// Mappa nome-icona (stringa storica, ex legatura del font MySuperIcons) →
// oggetto SVG Hugeicons ("Stroke Rounded", @hugeicons/core-free-icons).
// Le chiavi sono quelle già salvate nel codice e a DB (DataType.icon,
// SocialLink.icon): non rinominarle, anche se non rispecchiano più il nome
// dell'icona Hugeicons risolta.
export const ICON_MAP: Record<string, IconSvgElement> = {
  date_start: ArrowRightFromLineIcon,
  date_end: ArrowRightToLineIcon,
  quiz: Quiz03Icon,
  honour_star: HonourStarIcon,
  account_balance: BankIcon,
  add: Add01Icon,
  remove: Remove01Icon,
  add_a_photo: CameraAdd01Icon,
  add_photo_alternate: ImageAdd01Icon,
  arrow_back: ArrowLeft01Icon,
  arrow_drop_down: ArrowDown01Icon,
  arrow_forward: ArrowRight01Icon,
  article: NewspaperIcon,
  assignment: ClipboardIcon,
  attachment_square: AttachmentSquareIcon,
  auto_fix_high: MagicWand01Icon,
  auto_stories: BookOpen01Icon,
  badge: BadgeIcon,
  balance: BalanceScaleIcon,
  biotech: MicroscopeIcon,
  block: BlockedIcon,
  bookmark: Bookmark01Icon,
  call: PhoneCallIcon,
  camera: Camera01Icon,
  campaign: Megaphone03Icon,
  cancel: Cancel02Icon,
  card_membership: IdCardIcon,
  castle: CastleIcon,
  category: GridIcon,
  celebration: PartyIcon,
  check: CheckIcon,
  check_circle: CheckmarkCircle02Icon,
  chevron_left: ChevronLeftIcon,
  chevron_right: ChevronRightIcon,
  church: ChurchIcon,
  circle: CircleIcon,
  close: Cancel01Icon,
  confirmation_number: Ticket01Icon,
  construction: ConstructionIcon,
  contrast: ContrastIcon,
  credit_card: CreditCardIcon,
  credit_card_off: CreditCardNotAcceptIcon,
  dark_mode: Moon01Icon,
  delete: Delete01Icon,
  description: FileTextIcon,
  diamond: Diamond01Icon,
  link_back: LinkBackwardIcon,
  atomic_power: AtomicPowerIcon,
  bow_arrow: BowArrowIcon,
  handshake: HandshakeIcon,
  domain: Building01Icon,
  download: Download01Icon,
  circle_check: CircleCheckIcon,
  draw: PencilIcon,
  list: ListIcon,
  edit: Edit02Icon,
  edit_note: NoteEditIcon,
  chat_done: ChatDoneIcon,
  chat_favourite: ChatFavouriteIcon,
  chat_feedback: ChatFeedback01Icon,
  chat_cancel: ChatCancelIcon,
  identity_card: IdentityCardIcon,
  dashboard: DashboardCircleIcon,
  dashboard_add: DashboardSquareAddIcon,
  email: MailAtSign01Icon,
  email_open: MailOpenIcon,
  emoji_emotions: SmileIcon,
  emoji_events: TrophyIcon,
  error: AlertCircleIcon,
  thumb_up: ThumbsUpIcon,
  thumb_down: ThumbsDownIcon,
  police_badge: PoliceBadgeIcon,
  etsy: Store01Icon,
  event: Calendar03Icon,
  event_available: CalendarCheckIcon,
  event_busy: CalendarOffIcon,
  event_check: Appointment02Icon,
  expand_less: ChevronUpIcon,
  expand_more: ArrowDown01Icon,
  explore: Compass01Icon,
  facebook: Facebook01Icon,
  favorite: FavouriteIcon,
  file_copy: Copy01Icon,
  filter_list: FilterMailIcon,
  flag: Flag02Icon,
  flare: SparklesIcon,
  folder: Folder01Icon,
  font_download: TextFontIcon,
  gift: GiftIcon,
  gift_card: GiftCardIcon,
  forward_to_inbox: InboxUploadIcon,
  groups: UserGroup02Icon,
  undo: Undo03Icon,
  help_center: HelpCircleIcon,
  history: HistoryIcon,
  home: Home07Icon,
  hourglass: HourglassIcon,
  hub: NetworkIcon,
  image: Image01Icon,
  important_devices: LaptopPhoneSyncIcon,
  inbox: InboxIcon,
  info: InformationCircleIcon,
  insert_drive_file: File01Icon,
  instagram: InstagramIcon,
  interests: PuzzleIcon,
  inventory: Package01Icon,
  key: Key01Icon,
  keyboard_arrow_down: ArrowDown01Icon,
  keyboard_arrow_up: ArrowUp01Icon,
  label: Tag01Icon,
  landscape: Image02Icon,
  language: Globe02Icon,
  headmaster: LaurelWreathFirst01Icon,
  master: LaurelWreath01Icon,
  supporter: LaurelWreathLeft03Icon,
  support_agent: CustomerSupportIcon,
  light_mode: Sun01Icon,
  link: Link01Icon,
  local_fire_department: FlameIcon,
  location: Location06Icon,
  lock: LockKeyholeIcon,
  lock_open: LockOpenIcon,
  logout: Logout01Icon,
  loyalty: LoyaltyCardIcon,
  bulb_charging: BulbChargingIcon,
  xp: StarSquareIcon,
  downtime: FlashIcon,
  downtime_off: ZapOffIcon,
  mail: Mail01Icon,
  mail_outline: MailOpen01Icon,
  mailbox: Mailbox01Icon,
  manage_accounts: UserSettings02Icon,
  map: MapIcon,
  menu: MenuSquareIcon,
  menu_book: Book01Icon,
  talent: Medal04Icon,
  mosque: Mosque01Icon,
  music_note: MusicNote01Icon,
  notes_check: Note03Icon,
  notes: Note01Icon,
  bell: BellIcon,
  bell_ring: BellRingIcon,
  bell_off: BellOffIcon,
  star: StarIcon,
  paid: CoinsEuroIcon,
  palette: PaintbrushIcon,
  park: Tree01Icon,
  pause_circle: PauseCircleIcon,
  play_circle: PlayCircle02Icon,
  pause_circle_outline: PauseIcon,
  people: UserMultiple02Icon,
  person: User02Icon,
  person_add: UserAdd02Icon,
  person_off: UserRemove01Icon,
  pets: PawPrintIcon,
  photo_camera: Camera02Icon,
  photo_library: GalleryThumbnailsIcon,
  psychology: Brain01Icon,
  globe: GlobeIcon,
  radio_button_checked: CheckmarkCircle02Icon,
  radio_button_unchecked: CircleIcon,
  receipt_long: ReceiptTextIcon,
  refresh: Refresh01Icon,
  repeat: ArrowReloadHorizontalIcon,
  rocket_launch: RocketIcon,
  savings: SavingsIcon,
  schedule: Clock01Icon,
  school: SchoolIcon,
  science: BeakerIcon,
  search: Search01Icon,
  security: Shield01Icon,
  self_improvement: Yoga01Icon,
  sell: SaleTag01Icon,
  send: SendHorizontalIcon,
  settings: Settings03Icon,
  shield: Shield02Icon,
  skull: SkullIcon,
  profile: StudentCardIcon,
  spa: WellnessIcon,
  stars: StarsIcon,
  style: PaintBrush01Icon,
  chart_ring: ChartRingIcon,
  styles: PaintBrush02Icon,
  supervisor_account: UserCheck01Icon,
  temple_buddhist: ChinaTempleIcon,
  temple_hindu: DomeIcon,
  texture: BackgroundIcon,
  theater_mask: MaskTheater02Icon,
  toggle_off: ToggleOffIcon,
  toggle_on: ToggleOnIcon,
  token: TokenCircleIcon,
  tower: Castle02Icon,
  sparkle: SparkleIcon,
  travel_explore: GlobalSearchIcon,
  tune: SlidersHorizontalIcon,
  upcoming: Timer01Icon,
  upload_file: FileUploadIcon,
  verified: CheckmarkBadge01Icon,
  euro: EuroCircleIcon,
  percent: PercentIcon,
  visibility: ViewIcon,
  visibility_off: EyeOffIcon,
  warning: Alert02Icon,
  water_drop: DropletIcon,
  webhook: WebhookIcon,
  work: Briefcase04Icon,
  workspace_premium: Crown02Icon,
  message_incoming: MessageIncoming01Icon,
  message_multiple: MessageMultiple01Icon,
  checkcheck: CheckCheckIcon,
  hashtag: HashtagIcon,
  list_view: ListViewIcon,
  grid_view: GridTableIcon,
  combine: CombineIcon,
  learn: GraduationCapIcon,
  code: SourceCodeIcon,
  remove_circle: RemoveCircleIcon,
  add_circle: AddCircleIcon,
  text_bold: TextBoldIcon,
  text_italic: TextItalicIcon,
  text_align_left: TextAlignLeftIcon,
  text_align_center: TextAlignCenterIcon,
  text_align_right: TextAlignRightIcon,
  heading: HeadingIcon,
  block_quote: LeftToRightBlockQuoteIcon,
  horizontal_rule: SolidLine01Icon,
  unlink: Unlink01Icon,
  upload: Upload01Icon,
  apple: AppleIcon,
  smartphone: SmartPhone01Icon,
  check_box: CheckmarkSquare02Icon,
  check_box_outline_blank: SquareIcon,
  open_in_new: LinkSquare02Icon,
  sword: SwordIcon,
  swords: SwordsIcon,
  axe: AxeIcon,
  dagger: Knife01Icon,
  knight_shield: KnightShieldIcon,
  crown: CrownIcon,
  scroll: ScrollIcon,
  potion: PotionIcon,
  dice: DiceIcon,
  cards: CardsIcon,
  print: PrinterIcon,
  chess_knight: ChessKnightIcon,
  chess_king: ChessKingIcon,
  ghost: GhostIcon,
  moon_star: MoonStarIcon,
  eclipse: MoonEclipseIcon,
  snowflake: SnowflakeIcon,
  tornado: TornadoIcon,
  rainbow: RainbowIcon,
  mountain: MountainIcon,
  island: IslandIcon,
  trees: TreesIcon,
  leaf: Leaf01Icon,
  flower: FlowerIcon,
  mushroom: MushroomIcon,
  fish: FishIcon,
  bird: BirdIcon,
  horse: HorseIcon,
  feather: FeatherIcon,
  anchor: AnchorIcon,
  ship: ShipIcon,
  lighthouse: LighthouseIcon,
  bridge: BridgeIcon,
  tent: TentIcon,
  campfire: CampfireIcon,
  gold: GoldIngotsIcon,
  money_bag: MoneyBagIcon,
  hammer: HammerIcon,
  bomb: BombIcon,
  target: Target02Icon,
  bone: BoneIcon,
  heartbreak: HeartbreakIcon,
  first_aid: FirstAidKitIcon,
  pray: HandPrayerIcon,
  beer: BeerIcon,
  prison: PrisonIcon,
  gavel: GavelIcon,
  drum: DrumIcon,
  guitar: GuitarIcon,
  dna: DnaIcon,
  alien: AlienIcon,
  robot: RobotIcon,
  ufo: UfoIcon,
  biohazard: BiohazardIcon,
  clover: CloverIcon,
  lantern: LanternIcon,
  mask: MaskIcon,
  pyramid: PyramidIcon,
  gun: GunIcon,
  eye: EyeIcon,
};

// Icona neutra usata quando una chiave non è (più) presente in ICON_MAP
// (valori legacy o inattesi salvati a DB).
export const FALLBACK_ICON: IconSvgElement = HelpCircleIcon;
