/** Sottoinsieme curato per il pulsante emoji della toolbar (griglia 6x4) */
export const RICH_TEXT_EMOJI_SHORTCODES = [
  "smile",
  "laughing",
  "joy",
  "heart_eyes",
  "wink",
  "sunglasses",
  "thinking",
  "cry",
  "sob",
  "scream",
  "angry",
  "fire",
  "tada",
  "sparkles",
  "star",
  "rocket",
  "muscle",
  "clap",
  "pray",
  "wave",
  "+1",
  "ok_hand",
  "white_check_mark",
  "gift",
];
